import React from 'react'
import Head from 'next/head'
import { BsArrowRight as ArrowRight } from 'react-icons/bs'

import Header from '../components/Header'
import DetailPage from '../components/DetailPage'
import DetailWithImage from '../components/DetailWithImage'
import Insight from '../components/Insight'
import HideAndShow from '../components/HideAndShow'
import Grade from '../components/Grade'
import Footer from '../components/Footer'

import styles from '../styles/home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Knack Forge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <section className={styles.firstContact}>
          <div className={styles.firstContactText}>
            <h2>
              Trust is earned <br />
              through experience <br />
              <span className={styles.highlight}>let us earn yours</span>
            </h2>
            <p>Enterprise software solutions for business <br /> growth and performance</p>
          </div>

          <button className='btn btn-black'>
            View more
            <ArrowRight size={30} />
          </button>
          <div className={styles.arrows}>
            <div className={styles.row}>
              <div className='square' />
              <div className='square' />
            </div>
            <div className={styles.row}>
              <div className='square' />
              <div className='square' />
              <div className='square' />
            </div>
            <div className={styles.row}>
              <div className='square' />
              <div className='square' />
              <div className='square' />
              <div className='square' />
            </div>
          </div>
        </section>
        <section className={styles.sectionMargin}>
          <DetailPage
            currentPage='01'
            description='Our success rests in the relationship between people'
            title={<React.Fragment><h2>Products <br /> &amp; People</h2></React.Fragment>}
            borderBottom={false}
          />
          <DetailWithImage
            direction='row'
            title='Constant evolution, constant adaptation'
            description='We know what it takes to help your business prepare for the next generation of digital transformations. At KnackForge, we provide a comprehensive suite of solutions and services that technologically superior and comercially viable.'
            imgName='products-people.jpg'
            imgAlt='Woman writing tasks on postits with a men'
          />
        </section>
        <Insight
          text={<React.Fragment><h3>Let's work <span>together</span> to turn your <span>company's</span> vision into <span>software</span> solution with <span>staying</span> power.</h3></React.Fragment>}
        />
        <section className={styles.sectionMargin}>
          <DetailWithImage
            direction='reverse'
            title='Doing things differently'
            description='we employ a full team of development and management talent t complete work that always meets and exceeds your expectiations. We use open source platforms that ensure you retain ownership of every aspect of your project.'
            imgName='different.jpg'
            imgAlt='Eggs in tray on white surface'
          />
        </section>
        <section className={styles.sectionMargin}>
          <DetailPage
            currentPage='02'
            description='We have spent many year refining a process that delivers results'
            title={<React.Fragment><h2>Process <br /> &amp; Control</h2></React.Fragment>}
            borderBottom={true}
          />
          <HideAndShow
            title='cooperate'
            description='This is where your dreams get foundational bones to build on. As a team, we work together to set goals and timeline...'
          />
          <HideAndShow
            title='create'
            description='You can create high level products with your guts. Your ideias, our code, your success!'
          />
          <HideAndShow
            title='continue'
            description='Continue past projects without tear, share everything you wanted and we to the rest. Here we have a complete team to work for you.'
          />
        </section>
        <Insight
          text={<React.Fragment><h3>Letting go of <span>old ideias?</span> we're here <span>for it.</span></h3></React.Fragment>}
        />
        <section className={styles.sectionMargin}>
          <DetailPage
            currentPage='03'
            description='Choose from our service and find the tools you need'
            title={<React.Fragment><h2>Solution <br /> &amp; Technology</h2></React.Fragment>}
            borderBottom={true}
          />
        </section>
        <section className={styles.sectionMargin}>
          <Grade />
        </section>
      </main>
      <Footer />
    </div>
  )
}
